### ISSUE TITLE
JwtAuthentication Definition

### ISSUE THREAD

**Issue by SamuelRocha2015** [SamuelRocha2015/travel-manager-api#18]
JwtAuthentication is a DTO Class or a Model Class?

- If a DTO Class:
  - Move to DTO package.

- If a Model Class:
  - Remove serialization annotation 

https://github.com/SamuelRocha2015/travel-manager-api/blob/412a5ba1b5400083276bce82035c5ed93447e792/src/main/java/com/devs/travels/domain/JwtAuthentication.java#L10

**Comment by QueirozDavi** [comment]
JsonIncluded Removed
