### ISSUE TITLE
EmployeeController BUGS

### ISSUE THREAD

**Issue by SamuelRocha2015** [SamuelRocha2015/travel-manager-api#25]
In the class EmployeeController there are some errors:

1. Return a UserDTO:

![image](https://user-images.githubusercontent.com/11797557/70021317-4cee0d80-155e-11ea-89f4-3251b82faf7c.png)

2. The method is called "_createAppointment_":

![image](https://user-images.githubusercontent.com/11797557/70021388-95a5c680-155e-11ea-8b52-ec9b2b169a42.png)

**Comment by QueirozDavi** [comment]
I don't agree with the first point, this is a create context, we must return a User object, not a DTO. The second point was fixed.
