### ISSUE TITLE
DTOMapper BUGs

### ISSUE THREAD

**Issue by SamuelRocha2015** [SamuelRocha2015/travel-manager-api#26]
In the class DTOMapper there are some errors:

1. The method nomenclature is different:

   - What is the difference between _toEmployeeUserDTO_ and _toUserDto_?
   - Why does the method return a user, no a DTO?
   - Rename toJwtAthenticationDTO to toJwtAuthenticationDTO

![image](https://user-images.githubusercontent.com/11797557/70021651-68a5e380-155f-11ea-92f2-1abab3996854.png)

**Comment by SamuelRocha2015** [comment]
**_FIXED_**

![image](https://user-images.githubusercontent.com/11797557/70021855-1913e780-1560-11ea-8dea-b71c99786c2c.png)

**Comment by QueirozDavi** [comment]
The first name toEmployeeUserDTO was correct, its a mapper to EmployeeUser, note the constant mapper role with the value "ROLE_EMPLOYEE", i'm returning method to his first name, without suffix "DTO"

![image](https://user-images.githubusercontent.com/17460606/70052167-797f4500-15b1-11ea-9af3-7e6e0aaf8fc2.png)
 nomenclature.

**Comment by SamuelRocha2015** [comment]
Validate if toUser whitout target is valid for all user instances. 

See: https://github.com/backend-services/hosp-ms/blob/master/src/main/java/com/hosp/hospms/configs/DTOMapper.java
