### ISSUE TITLE
Use Feign to consume Token Generator API

### ISSUE THREAD

**Issue by QueirozDavi** [SamuelRocha2015/travel-manager-api#27]
Configure a client (or a module inside the project) to consume Token Generator API

**Tool:** Spring Boot Feign
**Token Generator API Swagger url:** https://token-generator-davi.herokuapp.com/swagger-ui.html

**Comment by SamuelRocha2015** [comment]
https://www.baeldung.com/spring-cloud-openfeign

**Comment by SamuelRocha2015** [comment]
@QueirozDavi 

Response body has " ", its correct? 

![image](https://user-images.githubusercontent.com/11797557/70105099-f04a2b80-160d-11ea-9d88-75645639044c.png)

**Comment by QueirozDavi** [comment]
> @QueirozDavi
> 
> Response body has " ", its correct?
> 
> ![image](https://user-images.githubusercontent.com/11797557/70105099-f04a2b80-160d-11ea-9d88-75645639044c.png)

yes it is correct, the web service provides a response who contains a token in a string with 5 characters. But for our project we need to pass user email, he will receive this token by e-mail.

But, for better use, i model a DTO with token response.

![image](https://user-images.githubusercontent.com/17460606/70137538-e277c300-166c-11ea-886c-b35ede456cff.png)
